// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyDuAn.Data;

#nullable disable

namespace QuanLyDuAn.Migrations
{
    [DbContext(typeof(WebContext))]
    [Migration("20240606082119_Initdb5")]
    partial class Initdb5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("QuanLyDuAn.Data.DungCu", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenDungCu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("dungCus");
                });

            modelBuilder.Entity("QuanLyDuAn.Data.PhongHoc", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ghiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenPhongHoc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("phongHocs");
                });

            modelBuilder.Entity("QuanLyDuAn.Data.PhongHoc_DungCu", b =>
                {
                    b.Property<string>("PhongHocDungCuId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DungCuId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("PhongHocId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PhongHocDungCuId");

                    b.HasIndex("DungCuId");

                    b.HasIndex("PhongHocId")
                        .IsUnique();

                    b.ToTable("phongHoc_DungCus");
                });

            modelBuilder.Entity("QuanLyDuAn.Data.PhongHoc_DungCu", b =>
                {
                    b.HasOne("QuanLyDuAn.Data.DungCu", "DungCu")
                        .WithMany()
                        .HasForeignKey("DungCuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyDuAn.Data.PhongHoc", "PhongHoc")
                        .WithOne("PhongHoc_DungCu")
                        .HasForeignKey("QuanLyDuAn.Data.PhongHoc_DungCu", "PhongHocId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DungCu");

                    b.Navigation("PhongHoc");
                });

            modelBuilder.Entity("QuanLyDuAn.Data.PhongHoc", b =>
                {
                    b.Navigation("PhongHoc_DungCu")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
